# Generated by Django 5.0.7 on 2024-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Interviewer', 'Interviewer')], default='Candidate', max_length=20),
        ),
    ]
