# Generated by Django 5.0.7 on 2024-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userdetail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('INTERVIEWER', 'Interviewer')], default='CANDIDATE', max_length=20),
        ),
    ]
