version: '3'
services:
  db:
    image: postgres:13
    container_name: hiretrack_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - hiretrack_network
  redis:
    image: redis:6
    container_name: hiretrack_redis
    ports:
      - "6379:6379"  # Map Redis port
    networks:
      - hiretrack_network
  web:
    build: .
    container_name: hiretrack_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE: postgres
    networks:
      - hiretrack_network
volumes:
  postgres_data:
networks:
  hiretrack_network:
    driver: bridge






